modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "tensura_ftb"
version = "${version}"
displayName = "TenSura Compat: FTB"
authors = "MinhEragon"
description = '''
Compatibility mod to bridge Tensura:Reincarnated and major FTB mods.
'''
#logoFile = ""

[[dependencies.tensura_ftb]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tensura_ftb]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tensura_ftb]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tensura_ftb.mixins.json"
